module SymbolicNeuralNetworks

    using AbstractNeuralNetworks
    using Symbolics
    # `SymbolicUtils` is imported (not just used transitively via `Symbolics`) because the code
    # generated by `build_kernel` references `SymbolicUtils.Code.create_array` directly; the name
    # must resolve in this module when the RuntimeGeneratedFunction runs.
    import SymbolicUtils
    using LinearAlgebra
    using RuntimeGeneratedFunctions
    # `QPTOAT` was `AbstractNeuralNetworks` 0.6's `(:q, :p)`-keyed alias; 0.7 replaced it with the
    # key-agnostic `ArrayOrNamedTuple` (JuliaGNI/AbstractNeuralNetworks.jl#31).
    using AbstractNeuralNetworks: ArrayOrNamedTuple

    import Latexify: _latexraw
    import AbstractNeuralNetworks: NeuralNetwork, Architecture, Model, UnknownArchitecture, AbstractExplicitLayer
    # The parameter container comes from its own package as of `AbstractNeuralNetworks` 0.7, and so
    # is the machinery for laying a nested set of arrays out in one flat vector: an equation set has
    # the same shape as a parameter set, so `flatten`/`unflatten` and `ParameterLayout` serve both
    # (see `flatten_equations`). The import is selective rather than a bare `using` so that it stays
    # visible which names in this module are somebody else's.
    import NeuralNetworkParameters: NetworkParameters, ParameterLayout, ParametersLayout,
                                    NestedLayout, TupleLayout, WrappedLayout, LeafLayout,
                                    flatten, unflatten, parameterlayout, parameterrange,
                                    flatlength, parameter_eltype, mapparameters
    import AbstractNeuralNetworks: architecture, model, params
    # defined for `AbstractLayer` upstream; extended to `Chain` in `symbolic_neuralnet.jl`
    import AbstractNeuralNetworks: input_dimension, output_dimension
    # the accessor for a `Chain`'s layers, which the layerwise pullback decomposes a model with
    import AbstractNeuralNetworks: layers
    # these types will be shifted to `GeometricOptimizers` once this package is ready
    import AbstractNeuralNetworks: NetworkLoss, AbstractPullback, FeedForwardLoss
    # the generated code may call `NaNMath` functions, so the name has to resolve in this module
    import Symbolics: NaNMath

    RuntimeGeneratedFunctions.init(@__MODULE__)

    export AbstractSymbolicNeuralNetwork
    export SymbolicNeuralNetwork
    export build_nn_function
    export SymbolicPullback

    include("symbolic_expressions.jl")

    include("symbolic_neuralnet/symbolic_variables.jl")
    include("symbolic_neuralnet/symbolic_neuralnet.jl")

    include("losses.jl")

    include("codegen/expression_rewriting.jl")
    include("codegen/kernels.jl")
    include("codegen/batched_function.jl")
    include("codegen/build_nn_function.jl")
    include("codegen/equation_sets.jl")

    include("derivatives/derivative.jl")
    include("derivatives/jacobian.jl")
    include("derivatives/gradient.jl")
    include("derivatives/pullback.jl")
    include("derivatives/layerwise_pullback.jl")
end
