module SymbolicNeuralNetworks

    using AbstractNeuralNetworks
    using Symbolics
    # `SymbolicUtils` is imported (not just used transitively via `Symbolics`) because the code
    # generated by `build_kernel` references `SymbolicUtils.Code.create_array` directly; the name
    # must resolve in this module when the RuntimeGeneratedFunction runs.
    import SymbolicUtils
    using LinearAlgebra
    using RuntimeGeneratedFunctions
    using AbstractNeuralNetworks: QPTOAT

    import Latexify: _latexraw
    import AbstractNeuralNetworks: NeuralNetwork, Architecture, Model, UnknownArchitecture, AbstractExplicitLayer, NeuralNetworkParameters
    import AbstractNeuralNetworks: architecture, model, params
    # these types will be shifted to `GeometricOptimizers` once this package is ready
    import AbstractNeuralNetworks: NetworkLoss, AbstractPullback, FeedForwardLoss
    # the generated code may call `NaNMath` functions, so the name has to resolve in this module
    import Symbolics: NaNMath

    RuntimeGeneratedFunctions.init(@__MODULE__)

    export AbstractSymbolicNeuralNetwork
    export SymbolicNeuralNetwork
    export build_nn_function
    export SymbolicPullback

    include("symbolic_expressions.jl")

    include("symbolic_neuralnet/symbolic_variables.jl")
    include("symbolic_neuralnet/symbolic_neuralnet.jl")

    include("losses.jl")

    include("codegen/expression_rewriting.jl")
    include("codegen/kernels.jl")
    include("codegen/batched_function.jl")
    include("codegen/build_nn_function.jl")
    include("codegen/equation_sets.jl")

    include("derivatives/derivative.jl")
    include("derivatives/jacobian.jl")
    include("derivatives/gradient.jl")
    include("derivatives/pullback.jl")
end
